dukecity_command_scheduler:

    # Scheduler will write output files here. set false to disable it.
    log_path: "/tmp/"

    # Add namespace you don't want to see its Command in the scheduler.
    excluded_command_namespaces:
        - _global
        - scheduler
        - server
        - container
        - config
        - generate
        - init
        - router
        - doctrine
        - debug
