#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Handler by EasyAdmin
#dukecity_command_scheduler:
#    resource: "@DukecityCommandSchedulerBundle/Resources/config/routing.php"
#    prefix:   /
