#index:
#    path: /
#    controller: App\Controller\DefaultController::index

dukecity_command_scheduler:
    resource: "@DukecityCommandSchedulerBundle/Resources/config/routing.php"
    prefix:   /
