name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: "8.0"
    - uses: "ramsey/composer-install@v1"
      env:
          APP_ENV: prod
      with:
        composer-options: "--prefer-dist --optimize-autoloader --no-dev --no-scripts"
    - name: Cache warmup
      env:
          APP_ENV: prod
      run: bin/console cache:clear
    - run: composer require bref/bref
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        #SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        # or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: upload assets
      run:  aws s3 sync public/ s3://sf-life-dev/ --delete --exclude index.php
