name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-west-3'
      APP_ENV: prod
      LAMBDA_TASK_ROOT: bref

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: "8.0"
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo, curl

    - name: "Set composer cache directory"
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: "Cache composer"
      uses: actions/cache@v2.1.2
      with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-8.0-composer-${{ hashFiles('composer.json') }}
          restore-keys: ${{ runner.os }}-8.0-composer-

    - uses: "ramsey/composer-install@v1"
      with:
        composer-options: "--prefer-dist --optimize-autoloader --no-dev --no-scripts"

    - name: Warmup cache so boost performance
      run: bin/console cache:warmup

    - name: Require bref/bref to deploy
      run: composer require bref/bref

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy

    - name: Upload assets to s3
      run:  aws s3 sync public/ s3://sf-life-dev/ --delete --exclude index.php

