name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-west-3'
      APP_ENV: prod
      APP_DEBUG: 0

    steps:
    - uses: actions/checkout@v2

    - uses: shivammathur/setup-php@v2
      with:
        php-version: "8.0"
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo, curl, apcu

    - uses: "ramsey/composer-install@v1"
      with:
        composer-options: "--prefer-dist --optimize-autoloader --no-dev --apcu-autoloader --no-scripts"
        
    - name: "Create cache"
      run: bin/console cache:warmup

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy

    - name: Upload assets to s3
      run:  aws s3 sync public/ s3://sf-life-prod/ --delete --exclude index.php

