name: Static code analysis

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: PHPStan
        uses: docker://jakzal/phpqa:php8.0-alpine
        with:
          args: phpstan analyse -c phpstan.neon

  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: PHP-CS-Fixer
        uses: docker://jakzal/phpqa:php8.0-alpine
        with:
          args: php-cs-fixer --dry-run --allow-risky=yes --no-interaction fix src/
